# OUTPUT_LANG_INDEX start from 0
generator-localization-nftify-landing-page:
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=3 SPREADSHEET_ID=1iI2_vbcDmbYM0mdIWBvcaYbKHwuG70JiZWiXYuduhwM GID_ID=NFTIFY-Landing-page OUTPUT_FOLDER=../src/i18n/locales/en/defaults.json
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=4 SPREADSHEET_ID=1iI2_vbcDmbYM0mdIWBvcaYbKHwuG70JiZWiXYuduhwM GID_ID=NFTIFY-Landing-page OUTPUT_FOLDER=../src/i18n/locales/ja/defaults.json
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=5 SPREADSHEET_ID=1iI2_vbcDmbYM0mdIWBvcaYbKHwuG70JiZWiXYuduhwM GID_ID=NFTIFY-Landing-page OUTPUT_FOLDER=../src/i18n/locales/ko/defaults.json
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=6 SPREADSHEET_ID=1iI2_vbcDmbYM0mdIWBvcaYbKHwuG70JiZWiXYuduhwM GID_ID=NFTIFY-Landing-page OUTPUT_FOLDER=../src/i18n/locales/cn/defaults.json